"use client";
import { useState } from "react";

export default function ComplaintPage() {
  const [form, setForm] = useState({ name: "", phone: "", orderNumber: "", message: "" }); const [sent, setSent] = useState(false); const [error, setError] = useState("");
  const submit = async () => { setError(""); if (!form.name || !form.phone || !form.message) { setError("Please fill in name, phone, and your message."); return; } const res = await fetch("/api/complaint", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (res.ok) setSent(true); else setError("Something went wrong. Please try again."); };
  if (sent) return <div className="mx-auto flex min-h-[65vh] max-w-lg flex-col items-center justify-center px-6 text-center"><span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-emerald-100 text-3xl text-emerald-700">✓</span><p className="mt-6 text-xs font-bold uppercase tracking-[.2em] text-violet-700">Message received</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950">Thanks for reaching out!</h1><p className="mt-3 leading-7 text-slate-500">We&apos;ve received your message and will get back to you shortly — or message us directly on WhatsApp anytime.</p></div>;
  const field = "w-full rounded-xl border border-slate-200 bg-slate-50 px-3 py-3 text-sm";
  return <div className="mx-auto max-w-5xl px-6 py-10 sm:py-16"><div className="overflow-hidden rounded-3xl border border-slate-200 bg-white shadow-[0_18px_45px_rgb(15_23_42_/_0.08)] md:grid md:grid-cols-[.8fr_1.2fr]"><aside className="relative overflow-hidden bg-slate-950 p-8 text-white"><div className="absolute inset-0 bg-[radial-gradient(circle_at_18%_18%,#7c3aed_0,transparent_35%),radial-gradient(circle_at_90%_90%,#0891b2_0,transparent_30%)]"/><div className="relative"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-white/10 text-xl">?</span><p className="mt-8 text-xs font-bold uppercase tracking-[.2em] text-violet-300">Support centre</p><h1 className="mt-3 text-3xl font-black tracking-tight">How can we help?</h1><p className="mt-4 text-sm leading-7 text-slate-300">Share feedback, a delivery concern, or a product issue. Our team will take it from here.</p><div className="mt-10 space-y-4 border-t border-white/10 pt-6 text-sm"><p><b className="block text-white">Response with care</b><span className="text-slate-400">We review every request personally.</span></p><p><b className="block text-white">Have an order number?</b><span className="text-slate-400">Add it to help us resolve things faster.</span></p></div></div></aside><section className="p-6 sm:p-8"><p className="text-xs font-bold uppercase tracking-[.2em] text-violet-700">Contact us</p><h2 className="mt-2 text-2xl font-black text-slate-950">Complaint / Feedback</h2><p className="mb-7 mt-2 text-sm leading-6 text-slate-500">You can also message us directly on WhatsApp for a faster response.</p><div className="space-y-3"><input className={field} placeholder="Your Name" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })}/><input className={field} placeholder="Phone / WhatsApp Number" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })}/><input className={field} placeholder="Order Number (optional)" value={form.orderNumber} onChange={(e) => setForm({ ...form, orderNumber: e.target.value })}/><textarea className={`${field} h-32`} placeholder="Tell us how we can help" value={form.message} onChange={(e) => setForm({ ...form, message: e.target.value })}/>{error && <p className="rounded-lg bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<button onClick={submit} className="w-full rounded-xl bg-slate-950 px-5 py-3 font-bold text-white transition hover:bg-violet-700 active:scale-[.99]">Send message →</button></div></section></div></div>;
}
